### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chycken** [K4ryuu/CS2_SimpleRanks#11]
Failed to load plugin /home/container/game/csgo/addons/counterstrikesharp/plugins/K4ryuuSimpleRanks/K4ryuuSimpleRanks.dll with error System.MissingMethodException: Method not found: 'CounterStrikeSharp.API.Core.CCSPlayerController CounterStrikeSharp.API.Utilities.GetPlayerFromIndex(Int32)'.
   at K4ryuuSimpleRanks.SimpleRanks.Load(Boolean hotReload)
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload)
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path)
   at CounterStrikeSharp.API.Core.GlobalContext.LoadAllPlugins()

what is it?

**Comment by K4ryuu** [comment]
Update your cssharp to the latest. You have an old installed.

**Comment by chycken** [comment]
Updated cssharp to the latest, and still got the error

**Comment by K4ryuu** [comment]
Type 'meta list' and paste here the response of the command.

**Comment by chycken** [comment]
It says that i have the 0.1.0 version of cssharp. Is that correct? Ive installed the latest build.

**Comment by chycken** [comment]
Updated again, its working now. Thanks
