### ISSUE TITLE
Support for not earning points during warmup

### ISSUE THREAD

**Issue by crashzk** [K4ryuu/CS2_SimpleRanks#12]
It would be interesting to add support for activating and deactivating the option to earn points during warmup.

**Comment by K4ryuu** [comment]
Greetings,
Thank you for the feedback. The feature has been implemented in the https://github.com/K4ryuu/CS2_SimpleRanks/commit/b91a6f67974e09f2bf6d716c44f3691c4863cf99 commit. The latest release also contains the patch.

Best Regards,
K4ryuu
