### ISSUE TITLE
Support for resetting points

### ISSUE THREAD

**Issue by crashzk** [K4ryuu/CS2_SimpleRanks#14]
It would be interesting to have support for the player and the admin to reset the players' points.

The option for the player to reset their own points would be interesting to include as an option to leave this feature activated or not for them.

And the option to reset the points of all players at once, only access for players with admin.

**Comment by K4ryuu** [comment]
Hello,
I appreciate your feedback. How would you like to determine who is an admin and who is not? By a list of steamids?

In the other hand it is a good idea tho, I can implement that the players could reset their own rank with a confirmation (to avoid trolls to abuse dumber players).

**Comment by crashzk** [comment]
List of administrators could be a steamid list as mentioned.

Yes, it would be interesting for the player to reset his own rating, but not those of other players, only if he is an administrator could he reset everyone's and such.

I thought of commands like this, for example:
- `!resetmyrank` - Player can use this command on himself and thereby reset his rank.
- `!resetrank` - This only administrator could use and it would reset a specific player or all players if using the **"all"** parameter along with the command.

**Comment by K4ryuu** [comment]
Noted, and I add this feature shortly (within few hours I get back to this project).

**Comment by K4ryuu** [comment]
The two new commands has been added to the plugin within an alpha release. 
The alpha release is available at https://github.com/K4ryuu/CS2_SimpleRanks/releases/tag/v1.4.1

The admins are loaded from a file, which is being created on first call of the admin command (if not exists), to the plugins folder of css. I will use this location in my plugins until there is no standard for this. That file (k4ryuu_admins.jsonc), will be listing the admins who are going to have access to the admin commands.

The command targeting is being solved with SteamID64 target currently as good old CS commands in SourcePawn, but I can change that later on if you have a better idea.

The self reset is just nothing extra.
