### ISSUE TITLE
does not load

### ISSUE THREAD

**Issue by asdfxD** [K4ryuu/CS2_SimpleRanks#15]
csharp running, added all files from this plugin in counterstrikesharp/plugins

+ created a folder in .../plugins/K4ryuuSimpleRanks 

but nothing works.

**Comment by K4ryuu** [comment]
Do you see any error log or console error? Without further information sadly I'm unable to help.

**Comment by K4ryuu** [comment]
I close the issue, because by our latest tests, there is no problems with the plugin at all currently.
