### ISSUE TITLE
[BUG] crash server

### ISSUE THREAD

**Issue by panikajo** [K4ryuu/CS2_SimpleRanks#16]
**Describe the bug**
I installed the plugin for the first time, connected the database and it crumbled

I am attaching a dump

[5e81c493-8c3b-470c-7e0758a5-17c795fe.dmp](https://github.com/K4ryuu/CS2_SimpleRanks/files/13289636/5e81c493-8c3b-470c-7e0758a5-17c795fe.dmp)

**Comment by K4ryuu** [comment]
Greetings,

Try to update your CSSharp version to the MinimumAPIVersion build. If that did not fix your problem, give me a feedback. 

If it fixed your problem, close the ticket.

Best Regards,
K4ryuu

**Comment by panikajo** [comment]
> Greetings,
> 
> Try to update your CSSharp version to the MinimumAPIVersion build. If that did not fix your problem, give me a feedback.
> 
> If it fixed your problem, close the ticket.
> 
> Best Regards, K4ryuu

[a75529ee-22f6-44f9-e64c2ea5-5506e155.dmp](https://github.com/K4ryuu/CS2_SimpleRanks/files/13295463/a75529ee-22f6-44f9-e64c2ea5-5506e155.dmp)

**Comment by K4ryuu** [comment]
Could you give me more informations about your server?

- OS
- MetaMod version
- CSS version
- Plugin version
- Possible console errors

I'm unable to open the dmp file with my reader tho

**Comment by panikajo** [comment]
> Could you give me more informations about your server?
> 
> * OS
> * MetaMod version
> * CSS version
> * Plugin version
> * Possible console errors
> 
> I'm unable to open the dmp file with my reader tho

debian 12
meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1256
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct 26 2023 10:57:52
    Built from: https://github.com/alliedmodders/metamod-source/commit/6ee74f0
    Build ID: 1256:6ee74f0
    http://www.metamodsource.net/
  [02] CounterStrikeSharp (0.1.0) by Roflmuffin
last release
no errors

**Comment by K4ryuu** [comment]
Please do the same as #17 to fix your issue.
