### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chycken** [K4ryuu/CS2_SimpleRanks#17]
Hello,
after installed this plugin, my server is crashing when i want to start it..
If I delete this plugin, the crash is gone.
Whats the problem? 

SRKHOST~ The server is marked as down...
SRKHOST~ ---------- The server is down (crash) ----------
SRKHOST~ Exit code: 139
SRKHOST~ Out of memory?: false

**Comment by K4ryuu** [comment]
Greetings,

If you send a bug report, follow the given template, which is loaded by default into the message and give a title after the BUG prefix.

Please provide me more informations about your server, such as:
- OS
- MetaMod version
- CSS version
- Plugin version
- Possible console errors

Best Regards,
K4ryuu

**Comment by chycken** [comment]
Linux
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1256
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct 26 2023 10:57:52
    Built from: https://github.com/alliedmodders/metamod-source/commit/6ee74f0
    Build ID: 1256:6ee74f0
    http://www.metamodsource.net/
meta list
Listing 3 plugins:
  [01] Advertisement (1.1) by Napas
  [02] CounterStrikeSharp (0.1.0) by Roflmuffin
  [03] Accelerator local (1.0.0) by Phoenix (˙·٠●Феникс●٠·˙), Asher Baker (asherkin)


Cant see any error

**Comment by K4ryuu** [comment]
When did you download CSS?

**Comment by chycken** [comment]
Updated cssharp 3 hrs ago, so the latest version

**Comment by K4ryuu** [comment]
Could you try the plugin with this version of CSSharp?

https://github.com/roflmuffin/CounterStrikeSharp/suites/17970489090/artifacts/1033400515

**Comment by chycken** [comment]
tried, and crached again. :c

**Comment by chycken** [comment]
Installed the entire cssharp, and its working. Thanks!!

**Comment by chycken** [comment]
Deleted and reinstalled the entire cssharp, and its working.
THANKS
