### ISSUE TITLE
[REQ] Support for earning points with grenade, zeus, knife kills

### ISSUE THREAD

**Issue by crashzk** [K4ryuu/CS2_SimpleRanks#19]
I believe it is interesting to provide an option for the player to earn points when he kills with the Zeus, Knife and HE, Molotov and Incendiaria grenades.

It would be possible?

Earn points if you kill by jumping too.

**Comment by K4ryuu** [comment]
Hello,
I am going to add every possible event that comes in my mind to the plugin within the next 24 hour.

Thank you for using my project!

Warm Regards,
K4ryuu

**Comment by K4ryuu** [comment]
Features has been implemented in V2.1.0. Thank you for the request.
