### ISSUE TITLE
Error mysql [BUG]

### ISSUE THREAD

**Issue by yabaldeu** [K4ryuu/CS2_SimpleRanks#2]
Error: Error while getting groupped points: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
Error: Error while getting or updating rank info: Can't call this method when MySqlDataReader is closed.

**Comment by yabaldeu** [comment]
The database itself did not want to automatically create a table. I had to do it manually. Writes data, but gives an error

**Comment by K4ryuu** [comment]
Greetings,
I appreciate your time and feedback.
The reported problems has been fixed now in the last patch: https://github.com/K4ryuu/CS2_SimpleRanks/commit/130cf2237f624f54333bf7c371c51b179fdcdca1

Have a great day! ❤️
