### ISSUE TITLE
[BUG] 2.0.2. Ranks are not visible in the tab

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/CS2_SimpleRanks#22]
OC Debian 11
Metamod:Source version 2.0.0-dev+1256
Counterstrikesharp-build-16-d4a2ae6
[6]: "Simple Ranks" (v2.0.2) by K4ryuu

`"ScoreboardRanks": true`
Ranks are not visible in the tab, even after rankup. At the same time information is displayed correctly in chat. 
There are no errors in the logs. `Simple Ranks [v2.0.2] by K4ryuu has been loaded.`

**Comment by K4ryuu** [comment]
Bug has been fixed in V2.1.0. Thank you for the report.
