### ISSUE TITLE
[BUG] no points when winning round and losing round

### ISSUE THREAD

**Issue by ghostt187** [K4ryuu/CS2_SimpleRanks#23]

**Comment by K4ryuu** [comment]
Bug has been fixed in V2.1.0. Thank you for the report.

**Comment by mrdiega** [comment]
> Bug has been fixed in V2.1.0. Thank you for the report.

2.1.0 not fixed

**Comment by ghostt187** [comment]
still not fixed

**Comment by K4ryuu** [comment]
Greetings,
The latest release possibly fixed this problem. 
Could you check on that please?
