### ISSUE TITLE
[BUG] !ranktop 

### ISSUE THREAD

**Issue by onlyguts** [K4ryuu/CS2_SimpleRanks#24]
When we do the !ranktop command, it displays our rank for all the players on the list, as shown in the image below:

![20231110025527_1](https://github.com/K4ryuu/CS2_SimpleRanks/assets/121417762/67030668-005d-45a3-a701-e1b6cd5e99eb)

My ranks :

Silver I - Exp: 0
Silver II - Exp: 50
Silver III - Exp: 100
Silver IV - Exp: 150
 Silver Elite - Exp: 200
 Silver Elite Master - Exp: 250
 Gold Nova I - Exp: 300
 
 ect ...

**Comment by K4ryuu** [comment]
Bug has been fixed in V2.1.0. Thank you for the report.
