### ISSUE TITLE
[REQ] Killed by bot take points

### ISSUE THREAD

**Issue by csportalsk** [K4ryuu/CS2_SimpleRanks#26]
If you play DM FFA `"FFAMode": true,` and there are some bots you get minus point when you killed by Bot. 
In config is `"PointsForBots": false,` - you can't get point for killing bot, but there is no parameter for _PointsBotsKill_ false.
You can lost all points when you play with 10 bots and 1 more players.
Could be posible to add this? :]

**Comment by K4ryuu** [comment]
Greetings,
The latest release possibly fixed this problem. 
Could you check on that please?

**Comment by csportalsk** [comment]
Now its OK. Good job. Thank you :]
