### ISSUE TITLE
!rank not working, points not saved.

### ISSUE THREAD

**Issue by asdfxD** [K4ryuu/CS2_SimpleRanks#28]
plugin works, but !rank is not working,  points won't be saved in external mysql server but plugin creates the mysql table k4ranks.

edit: i have a ' in front of my name, mysql does not add my name. if i change my name to test, it works fine.

i change collation to utf8mb4_unicode_ci, still does not work, it does not add me when i have ' in front of my name for example 'TESTUSERNAME

**Comment by K4ryuu** [comment]
Greetings,
The latest release possibly fixed this problem. 
Could you check on that please?

**Comment by asdfxD** [comment]
thanks, yes it works now with ' but it crashes the server on startup.

1.)
cssharp meta auto load with .vdf
K4ryuuSimpleRanks in plugins folder will crash server at startup.

2.)
cssharp meta auto load with .vdf
K4ryuuSimpleRanks in plugins/disabled folder no server crash at startup.

3.)
cssharp loaded **manually**
K4ryuuSimpleRanks in plugins folder no server crash at startup.
also starting the server first and than load cssharp manually with this plugin enabled does not crash the server, but it crashes when you auto load cssharp and this plugin.

**Comment by K4ryuu** [comment]
The problem was solved. Please check the latest.

**Comment by asdfxD** [comment]
y, works fine. thanks for fast response and fixing it.

**Comment by K4ryuu** [comment]
No problem at all. Keep updated. ❤️
