### ISSUE TITLE
Error: Error while getting groupped points

### ISSUE THREAD

**Issue by MinnDe** [K4ryuu/CS2_SimpleRanks#3]
First of all, when the server was rebooted, no new table was created in the database.
After using the command:

`CREATE TABLE IF NOT EXISTS `k4ranks` (`id` MEDIUMINT(8) AUTO_INCREMENT PRIMARY KEY, `steam_id` VARCHAR(32) NOT NULL, `rank` VARCHAR(64) DEFAULT NULL, `points` INT(11) NOT NULL, UNIQUE (`steam_id`));`

After rebooting the server, the server successfully communicates with the database and data is written.
After using the !rank command, the following error occurs:

![Screenshot_1](https://github.com/K4ryuu/CS2_SimpleRanks/assets/64688461/4e22dae2-7698-4388-a096-ffac5bf7b6cd)

**Comment by MinnDe** [comment]
After a while the problem simply disappeared, and now the !rank command no longer produces any error.

**Comment by K4ryuu** [comment]
Greetings,
I appreciate your time and feedback.
The reported problems has been fixed now in the last patch: https://github.com/K4ryuu/CS2_SimpleRanks/commit/d7f126c629a732ebaadf81d56bdb1fb908fea504

Have a great day! ❤️
