### ISSUE TITLE
[BUG] Lags when killing an enemy

### ISSUE THREAD

**Issue by serv-up** [K4ryuu/CS2_SimpleRanks#4]
When you kill an opponent, it starts to lag a lot

**Comment by yabaldeu** [comment]
I couldn't record a video, but lags occur when you kill, kill you or kill any other person on the server

**Comment by serv-up** [comment]
You can check it out here: https://youtu.be/52Gg4IrKJRo

**Comment by K4ryuu** [comment]
Greetings,
I appreciate your time and feedback.
The reported problems has been fixed now in the last patch: https://github.com/K4ryuu/CS2_SimpleRanks/commit/d7f126c629a732ebaadf81d56bdb1fb908fea504

Have a great day! ❤️
