### ISSUE TITLE
[BUG] in FFA not expected behaviour

### ISSUE THREAD

**Issue by jovicdev97** [K4ryuu/CS2_SimpleRanks#5]
**Describe the bug**
Great Plugin! However its not behaving normal in FFA servers, when you kill a teammate u get -XP.

**To Reproduce**
1. Change Setting to FFA
2. Kill Teammate
3. See error in chat

**Expected behavior**
Should give u regular XP for the kill, because FFA is enabled.

**Comment by K4ryuu** [comment]
Greetings,
I will update the plugin with the followings shortly:

- Rank toplist
- FFA mode

**Comment by jovicdev97** [comment]
Awesome!

**Comment by K4ryuu** [comment]
I have implemented FFA mode compatibility, which can be enabled through the config file with `FFAMode = true`. Also added the top list as a side quest.

Commit: https://github.com/K4ryuu/CS2_SimpleRanks/commit/de53407b133c7bf97086f788b1c0f58bd86e90ed
