### ISSUE TITLE
New Release Scoreboard ranks

### ISSUE THREAD

**Issue by itsAudioo** [K4ryuu/CS2_SimpleRanks#9]
I just tested your new release, and "ScoreboardRanks": is set to true, but I dont get ranks on scoreboard, what did i do wrong :P. I Reinstalled everything except ranks.json

**Comment by ry1nffx11** [comment]
@audiomaster99 can u give me your discord pls

**Comment by K4ryuu** [comment]
Update your CSSharp to latest build. Clan is settable since one of the fresh version.

**Comment by itsAudioo** [comment]
> Update your CSSharp to latest build. Clan is settable since one of the fresh version.

could you provide the link to lates CSS build, i downloaded like 10 today dont know which one to use

**Comment by K4ryuu** [comment]
The last one haha.
Currently it's: https://github.com/roflmuffin/CounterStrikeSharp/actions/runs/6772103962

**Comment by itsAudioo** [comment]
> The last one haha. Currently it's: https://github.com/roflmuffin/CounterStrikeSharp/actions/runs/6772103962

ok just tested this, and tag on scorboard show only on end of the round if u die, then it dissapears.

**Comment by K4ryuu** [comment]
Do you have something which sets clan tags also? In the other hand the clan tag gets updated on point changes. If it is required I can force it with timer.

**Comment by itsAudioo** [comment]
> Do you have something which sets clan tags also? In the other hand the clan tag gets updated on point changes. If it is required I can force it with timer.

actually i do have tags for admins on cs2fixes. Im guessing its breaking rank tags  sadly

**Comment by K4ryuu** [comment]
That's for sure, yes.

**Comment by itsAudioo** [comment]
> That's for sure, yes.

ah, now i gotta find a way to disable it in cs2fixes :) gl to me
